# Site settings
title: DEVSIA
SEOTitle: DEVELOPER | DEVSIA Blog
header-img: img/coding2.gif
email: ekfqlwcjswl@gmail.com
description: "블록체인 블로그"
keyword: "kyunghyunhan, Blog, 블로그, Rust, 러스트, Solidity, 솔리디티, Blockchain, 블록체인, 백엔드, Backend, Web, web3, React"
url: "https://kyunghyunhan.github.io/" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
github_username: kyunghyunhan
linkedin_username: kyunghyun-han-8b0956244
instargram_username: hyun__dev

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Netease settings
netease_comment: false

# Analytics settings
# Analytics
analytics:
  provider:
    "google-gtag"
    # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id: "G-LR78DZXZW1"
    anonymize_ip: # true, false (default)
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: "G-LR78DZXZW1" # Format: UA-xxxxxx-xx
ga_domain: https://kyunghyunhan.github.io/

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "블록체인 블로그"
sidebar-avatar: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAoHCBUVFRgWFhYYGRgaHBwaHBwaGhgcHh4aGhocGhkcGhocIS4lHB4rIRoaJjgmKy8xNTU1GiQ7QDs0Py40NTEBDAwMEA8QGBISGjQhISE0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ/ND8xMTQxNP/AABEIAQMAwgMBIgACEQEDEQH/xAAbAAACAwEBAQAAAAAAAAAAAAACAwAEBQEGB//EADsQAAEDAgMFBgUDBAEEAwAAAAEAAhEDIQQxQRJRYXHwBYGRobHBBhMi0eEyQlIUYnLxggcVorIjJJL/xAAYAQEBAQEBAAAAAAAAAAAAAAAAAQIDBP/EAB0RAQEBAQADAQEBAAAAAAAAAAABEQIDEiExQVH/2gAMAwEAAhEDEQA/APm5ZqFx3NJNUncg+Ydy4Y7rlN+kprKioNtdWWXQXadchehwXxNiGNDRUdAy1jxXlQ7ejFVQe4p/FeIOVXyb9lpdnfFlUO/+R5c2I+kNBnfxXzplY71co40iJupkH2XsfENrN27gCRpJ6BVXtntduE2AWOex0gEESCNCDw9Fj/BfblJzDTLtl4JMG0i2R1Sv+oGIGxSE/ucfJJP4jaw3xdhniS4s/wAhC0sP2rQf+iqw/wDIL48zEM1KYazdASeAVw19mDgcioV86+F8WQHbRc2DkSclcpfFri97Wtsy21tWPks4r3IcRqUQqnnzXj6XxO/9zGnlIVzD/E7HfqY9vgUwejc9pzaCgFGno2OULOp9sUXfvjnZW6eIY79LgeRCaCOBYcnRzWB8SdiBzQ91VrAJiRMnhBklaXafazaQgfU/doOZ9l5rE1XPO28yTkNw4DQJqzm/rDp4IDP6j5eCc2hOauvbr5JLnws3I2q1SGgk6eyxOzg5zjBiTLjuGccyrfauJtCbgMJsMaZIcbuGlxkpLJLWpF7aUQqLm6PDtYNwQvAUDkhz16nlMZZPYLZJTGoy9QDWaUpoIVlhBRMpiUC2poduXKjETAgZSeRfJXa+Pe8Na9xcGzszeJzVFhRvbABU0W6b4vA7wrVLEn+I7lRpvlqCpUj6R3qe1XHpMJiWFhDgboGMYBYWmyyadTZE6JTcY5xACzq+r0zHtRnEsaLlZdPDu2QSRKR/Tve8MaC5xsAO/PdzTaerbZjGb1aNUPAgxyz8U7s74VaADVeXO3NMAd+Z8lpu7ApxDS9pGV58Qc1r16pOuZWMGXG4I3/y8keLwb6UB15ycMj9jwVR9W0cFL8b2UVapZZ2LrQCnvcT1vWbjqL84kaxmPusftPxTp0tt4nfK2yqPZrLly0CFm1rkEKIlFGnz2k/dluTTTm6Rh3jvVsL015nKTY6yXShqOSqb5QGTBVhiQrDbBTQRKKEhxuCEYeouGMXamVkO7rio982KKbhXZo8OzaJdpoeB08eoS2WBnrVWaDQGhpttWP+Rt5i3PkoFVHT/irHZVG5ectELKB2YOcweYz64FW3w0BjdBKzfjUTE45wFl6b4XY1lF2JqkCQTtH9rBme+PReKxZgE6fZafx3jDTw+HwzbBzQ53EMADR/+pP/ABC34udrHkuRztX4+rPeW0IpsmA4gOe4byDIbyg81odifEGMcA7b2xqHNb5FgBHmvnNDNfavhLtHA4bCsJbtVCJfIH6joOC9F5cJWnhMSzFUnDJws9p/Ux37XDeNx4EFeOxLS15ac2ktPMIMD280dohzBssqO2Htn+Zlvg7Zjgr/AMVs2MRItttB74LZ/wDFcfLPmu3i6+4QynbeoGrvZr5ZffBVv5QJyXPmfHTq/VUYVhFx4W9EJ7Pbo5w7yr7qZCBUUv8At/8Ae7y+y4rqizkXXydjFcp5X65pTSIgymsysfELrXIqoYSmFdrPvuXWAJgc05I2vQMCjnbs1loZchY66XUtquMnvQXWFQvVbbORTNu3W9Qh9MyI32Her7qcu2d0fg9xjuVbsuntPYOMmeRW9Wwuy4u6jLr8IKzgTBA/UP8AzB9yPMoMQ4HT6gfEbx3K01kgjOSCOdp8cxzKS5xdEi4sRuItHhCnUWMvtK1O2so/+oDtp+Hf+11FsdznE/8AsE7tHDS2xzGXHNSvQ/qsA3ZE1cKTLdTSNjA4Q0/8SuviuMeWPK4RhLgB1vXoMNVO0WTwF7WGixcHV2TbOIFp91b7LfD9S4fpbEy6QIOotJ7l1tcYt4FrjjKTdfm0xb/Jq+gfGbx81nBg1ylzlgfAfZjq+KdiXNhlMkg3ALyIAE7mmTuJatLtvGh731JFzss3QLNMcc+9cfNfjr4p90nsjENLiQZBF5GuRWy1m5ec7JrQ+XTskFpOknhoF6anTi2YXPn8dOv0TUL2A8E3ZhCRvVCfluUT4UQfIpkW9o9VHdyRh6xNre65Uqwfwuln1gdXTLyC6xvDLh7qnUrz9Nkyg8950yV9fiatyMuvBC1+W+Utz+XkkufeT3Keq6a98ut1uTQ+AN/+7qi15zyTXVMhuS8rqwBxRh+l0hzrT1yT6G/7LNixufD1GagO4L0uNGQ327l57sBw+p1+5bL68uE5JIlrQ7NwAc0g3/SfD/S2v+z03EOLRJAmOEQqnZOm4yFuseGi+mauRNeY+Kex2MZttMZCD6heKwjKtGqKtJ0O3H9LhucvW9udqnEfQ0gBpyzJjevPf05Bz8lzvWX46TnZ9W3dm4PEu23beEqG7hsh9InUjINng4cld7D+CsOXycWKv9tMNYSNZO04xyjmkYevsGN+SLD4OocTRfTb9Ye0kgfsJ+uTuic1vjy23Kx145Psex7ap/0+FDaLAxoIZAsA0gzHEnM8SvHNwrSZe6d2gJ5Tkvo2Owpq03M3gRO8EEei8hX7Kcx4+Y0xpNweRFiseXd1fHmYyHMYASDtTYDTwyXoOy6pcwA/qbbmsvGPY5+ywAbOZA15IMPUc1wNxFrn13rnOsdbNekhIduS6ePBFx5of6xhz2geRPmF0nUY9aZIUQfOp/zHh+FE2GPijXXso+oSclGMTm0gvTscIrMZdOpmLo3s3ISwqbq5hTgc0QvvTWsjQkqO8OWaaYWzkrVOgQJtKS0xB3ojUIPfI/CzdrUG9uUnwT2CAktYXLSw2G2xZY6rUjX7HpbNP/LNWq1NwYC2doK3hsNFMCDkjZTOybwprK72T2iC0XjeNx1lauPx7RTsbuELxxplp2mG+vFW8M59a2zEGwn0Wv2Nc8/fqrhaJDnSZlxPIbloOwu2NptxrwhMf2dXYNptInfe/cIurPZ1EtY9zQSMyL56/wClz9drv11z6/GdhsO4vaxoJcTA5nfwi65238XDCk4fC7JeCRUrEB31CxDBlY6m1og5p1PEOpUsViSSHspwwnR9Q7DT3e6+ZvN118XM/Xl8nV/HpK/xjjA/abiag7wR3tIjyXu/hD4vbjR/TYkND3D6Xt+kOI/9X62seGS+PTMK3gajmPa5pILSCDuIMgjkV1vMscpfr6n2h2eMMXsMudntHMtOR8vEFJw7Jb+Fv9tOFfDUMSBdzWzye3ajuI81nto7LRYzn1wXh75zrHs4u86SGRE5FPbRBCa+iS3x/B9Vyg0wOUd3UJ6taT/RjcF1W9griepr4a2UQadUTmkoNrRezXmkM+UdCiDHb2oGVDvT2tKzbVKeDuQMdBVh07lWdySfQxzYgnfnfVMaJOWWSKk2b5daqyymCQVm9EgMO64zuFsYYll457jyWeKVx1dW6rHNFiZgH1lc7frcj2OFqB9MEZQquGuSJAWb8P4s7Ba7L0nLuVqs+CYVlZsxYqUNmYKvdgMBbPE+KzadcxByV7s14ZllMrXJa9lhqlhxsrAqDVYeF7QYLTY5jWd4Oq52rittmy10jMFv6hGYc3MDiFbcT9Y/alL51HG0mCXOYKjANdioXkAdwHeF8sNAm6+hYbFPoPp12EvaHHaGpYQA5p3OFjG8DQyp278Gl/8A9jBRUpVPq2AQHNnPYBzbn9OYyg6Xx9fMZ75+vnjRGbfJNYJORWu3sfEl2z/T1trd8t8+EL3fwb8DPa9tfEtDdkgspyCdoXDnxYRmG784iD01iR6Q4J1PAUaRA2mtptM/yDb+hVShgtTb0SPjDt8sqMYyCGXdrfKByv4lZjfiIvGyWgA964dc23ZHo46nMyvS/KjSQhcWN/b6LOwuLJ0V9j50tuKnrWr3/kT5h3NURbDd/mor6s+9fDizRLfQVgtz8Ou5HC2wzXUiE5kiOSsFk+QSXhN0EHzlY8Ulw2rwjDZ5qzQoSFNxYHDshXqLYcJyK4aMR5p9IAyD1uKxVMFEF+zvb55q4aEtjcD3jqVXFRvhPp6pjMSSCNk5LGLqthgaZIM7J1+60acVCQDcQfLMIqLXHT6TnOk8UXZ/ZzgS7IZA6wk1bijXx/yyQc1qdlY1tUfTZ0fpOfEqxieymPzCzKvYBY4PpPIOn25LrMc7KuYytUYY2SU+jjTLXa6c/wCJOmcg6THJLMXXaYqU9r+4bt6Q+oHTFN4J04j/AGfBYu61MXqrQ6XsBIP62b95bGThn+CQg7L7VqYZ5+U6WOvsuuw92bHZZcMxCW35lnMYZkbQJA2h7HjwVtnZhJ2nCWOz0I195G6SMlqT+pb/ABu4b47YTsOov2svpc0jxMHyVjEdq4msIYG0mHMhxc8jgYAHrxWZhuyabY+hs74utmjTEQFq9ak5xUZ2PRJlzNonfJVhuAps/SxscGjxH2VprYzTIU0JaxsWiNIXHNTHMi4HMe448ERYCLZb1FhPcombJ3Lqar4WyrJIHd4/6TmjLw7lltJbdX6dUGJzXSxz04jcqdexTm1oSngu0TDQ0zdXqDxZVaWFJ8Vo4fA79yl5XRNfuumUsMSZVqlhwICt4enkesh+VMXSaOFAAtwWrQoi1ktlK0dX/K0KDcj1xUsHGUAZG8R15K1hmyL8jzFio1mqaxsPj+VxzGfse9ZaEKWiW2naCroYl1qeR0KBfypSn4cZq3TB5x5jcmmnkUVTos63K1SbpobHnp7oWs2TflKc1uYREYyLJ9InNcaJt+4JrTIO8Z/dA5hkKBBScMj1zTiyQgJqBwLbjLUe49wjaicVQuG7/NRT5Q/gFEHwOowuAtARMoHVXGs8Eeyu7hquyknMpxomMpaotnVFRjo06CsNxBGiS1vXJdAsoHHGu4ZomY54IyVaFx2/l9lMXWkztB4PNW8N2i6Y7/usdqNrtQpi69PSxZOqacQYnVpkcsneV+5ZOFfK0aKzYsrYpVSU9rpELNwJj6f4mO7Q+EK+zNZsUdNx3ZdFWRa+mvA70kNvYceasUs4UaA9nghaIsZVprNPBceyeeh9+X+0UszLXDl9pVh7cnCJ1QMuLjgefBFRfBhBxzdR1wRsfEXt14flRwg8D14pJlvLX2KIuBGFWa+D11+E9yo7A6lRSD0FEHxQhd4oiFGjRd3BA3koubCLWFoRq6AulRqyoChbkUwIGhAymjbYwhbnzRlqgv4Y3hatI5FZGHOR8fda2GcD3rNai8ww9p/lbvF2+/gtNgsspjCQW65t5i4+y08LU2gDvWa0sM9LqxsefkUmln5Kyzdoc+Cy0OncIi3uI9OvXkpseN+/ija7I9cR7+KgW1uvUhR7Jy7vdNLBfrr8JTZnZmTmOSKNjw4Ql7JyOY9FC2DI7wuuM3RC8raacvuE5j8get0IX3zy9DvQl2Y1HXgqLO0N/mokbR3jwUV0fImhc2UagC7OCLg3roYoQgigUK60IoXWXIvKKx9UJEIO80wH8pbQjbMoLeHEa5+ui1MLMx1GvXFZ2GE2WlhuOY69FmrGrQCs4Sxc0f5Dk78yq2GO5WXmC1+4weTreseKy20WNm6sMFo7u7qfJJpGQnUs7rNFpjJA1I8wUqoyPqBsSO46HkmskW1zHuF2pA4g5/frco0WDIy5jd11mgqM1m4y9+uK6fpzyNj7FNOY39eqBYg38QfMJBOy6DkeuuoY4bJnTXl7LlVkjlqOskHIixQPaQQNRkd43LrDP0nuR3P06jI8skC/njf14KJvzB1KiD5G4aroChXGGy7uDgmFCYRFccEHF2VxRxRQsuO/0umbU55JYGnV0wIBHAowhYJvKZCC1hytOicj49eay8MtXDFZqxpYFgEjI58wtBrJsciIPfr7rMpenmCtNsgDVZaWcA8kAHMEtPd/o+CuuGqzaZh/B4n/AJCAfY+K1GXCimtMgEJhNr5HMccuu5Kpn1TGu1KlWALLbJvuny7ktlrbvTrzCsPbIjUZeyqvJz1b+oeqinZ2lJZa2hyTGOFyMjf7/fxXHQ4ddT9igVXZBkZa8OK645EZjrrmutdAg5ZXzH4QUqguJmPTTrggd8zh6fdRL+Xy67l1B8mi6B9rozZR4XdwDt+K5kugKSgFzoXSFwiSuvQca1FtXUQx6oD2kTAlE3RscirmHK0MPM2KzsOVpYQdeqlI0sMRIPcVpYZ1y3QLKonxy+y0qBhwO+x68FitxbrtMT/GHDu/UPCfBaNB8gEahVqTbBTADZJZ/E25ZjyI80VfaIRgb1B+UbQs1Y43LiJ664Jb9/cUx9oI71x3kfVZVTb9Do0NxzRRB4HqOB/C7iGydk56HigZ9QIOfv1HcgeBPI5Ks5my6w61R0bS077cCU1zJ5hFKgdEqI9jkog+SuEgLhUzCFi9Tzuri6uaoJF1CoTmoxBPsu7K4FHaLIjzBKJgQ1L3XWPQWcOFp4YeazaRgrRwjj7pVjRZIuNxB9lfw8Fs7x7WVKndW6LbcFzrca2GqSPPrzRVjsva8ZfpPddvv5KrhrHPo3+6u1GbTC0ZkSP8hceiK0GRARKrgKu0xp1GauLDTjh5oRBt1OhRlLdmVBx7Z0uFWeyPq7nct/W9WZuN/skvz4GfyEUD5iRnr90xhm+uRQMGyY0zHJDtFpykILEKLm0z+Xmog+P08kMwe9db7rjsu9ep5xaqOzXGqFAJzPco3JccUTdBx9EHUbQo0KDNAA3KBgRuYuNash9I3WhhneSzaButPDtACVY06N+u9XKTsxwlUqWYVuiL9581itxeoO+odcR7rTpOgBZTRad0HrzWlTyUV3DO2Kjm/td9Q78/OfFaYWXiRAa8fsIn/F1j5wtRhkLFaQoCmEKFRSQfJC9uh1NkTs1wifbkgADQ6IR1yRVJgHdn7oeI6690C/l/2jwCiZsnj5KIPkLc1HqKL1POJqAqKIFpmo5LqiA2qBdUQGUhRRSh9HNaLMlFFKRp4fJXG5jmFFFiukXG+y0MNkOSiizVWM2vH9h9E7AGWN5KKLNaWlCooopNXRcpfcKKIOPzSKeR5n1P3UUQLdmVFFEV/9k=" # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends:
  [
    { title: "Quest", href: "https://github.com/ProjectOneQuest" },
    { title: "Wongcheol", href: "https://github.com/woongcheol" },
    { title: "seonghun", href: "https://github.com/kim-seung-hun" },
  ]
